version: "1"

services:
  web:
    image: node:18-alpine
    ports:
      - "80:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    command: >
      bash -c "echo 'const http = require(\"http\");
      http.createServer((req, res) => res.send(\"Hola desde una replica\")).listen(3000);'
      > index.js && node index.js"
